### ISSUE TITLE
Set PANOSE flag to "Monospaced"?

### ISSUE THREAD

**Issue by cpkio** [dse/dse-typewriter-font#1]
If this font _is_ monospaced, please set an appropriate PANOSE tag so it could be recognized by font managers and other software.

**Comment by dse** [comment]
So sorry I neglected this issue.  I did do some tweaking on the PANOSE flag last year so can you confirm that it's fixed in the latest .ttfs?

**Comment by cpkio** [comment]
It seems it's fixed. Thanks.
